/*
 * Copyright (c) 2007-2020 Texas A&M University System
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the
 *   distribution.
 * - Neither the name of the copyright holders nor the names of
 *   its contributors may be used to endorse or promote products derived
 *   from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/**
 * This file is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * It includes values of some nesC constants from
 * /opt/tinyos-2.1.1/tos/lib/serial/Serial.h.
 */

enum {
    SERIAL_HDLC_CTLESC_BYTE = 125,
    SERIAL_TOS_SERIAL_802_15_4_ID = 2,
    SERIAL_SERIAL_PROTO_ACK = 67,
    SERIAL_TOS_SERIAL_CC1000_ID = 1,
    SERIAL_SERIAL_PROTO_PACKET_NOACK = 69,
    SERIAL_SERIAL_PROTO_PACKET_UNKNOWN = 255,
    SERIAL_HDLC_FLAG_BYTE = 126,
    SERIAL_TOS_SERIAL_ACTIVE_MESSAGE_ID = 0,
    SERIAL_TOS_SERIAL_UNKNOWN_ID = 255,
    SERIAL_SERIAL_PROTO_PACKET_ACK = 68
};
